### ISSUE TITLE
two potential errors in bees

### ISSUE THREAD

**Issue by ericpgreen** [NicciPotts/tidytuesday#1]
Great map! In attempting to reproduce this, I came across two potential errors. 

1. Missing `library(geojsonio)` for running `geojson_read()`?

2. Did you mean to include the `+` between commands?

```
coord_map() +
ggsave("bees.png", height = 12.25, width = 18)
```

Or 

```
coord_map() 
ggsave("bees.png", height = 12.25, width = 18)
```

**Comment by NicciPotts** [comment]
Thanks for this! 

I added library(geojsonio)  and removed the additional '+'
